"""Update Feedback model

Revision ID: 5c899505b0bd
Revises: 
Create Date: 2024-06-27 19:03:42.578379

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5c899505b0bd'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('feedback', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.Integer(), nullable=False))
        batch_op.drop_column('decision_id')
        batch_op.create_foreign_key('fk_feedback_user_id', 'user', ['user_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('feedback', schema=None) as batch_op:
        batch_op.drop_constraint('fk_feedback_user_id', type_='foreignkey')
        batch_op.add_column(sa.Column('decision_id', sa.INTEGER(), nullable=False))
        batch_op.drop_column('user_id')

    # ### end Alembic commands ###
