"""Update Decision model

Revision ID: 8ff1565872ff
Revises: 00555d327b79
Create Date: 2024-07-02 18:07:36.465106

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8ff1565872ff'
down_revision = '00555d327b79'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('decision', schema=None) as batch_op:
        batch_op.add_column(sa.Column('current_step', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('data', sa.JSON(), nullable=False))
        batch_op.drop_column('response')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('decision', schema=None) as batch_op:
        batch_op.add_column(sa.Column('response', sa.TEXT(), nullable=False))
        batch_op.drop_column('data')
        batch_op.drop_column('current_step')

    # ### end Alembic commands ###
