"""Add summary field to Decision model.

Revision ID: cca6b7c9cd21
Revises: 
Create Date: 2024-07-10 16:13:07.251617

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cca6b7c9cd21'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('decision', schema=None) as batch_op:
        batch_op.add_column(sa.Column('summary', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('decision', schema=None) as batch_op:
        batch_op.drop_column('summary')

    # ### end Alembic commands ###
